AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Infrastructure for FinTech Pulse

Resources:
  SaveUserDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/saveUserData.handler
      Runtime: nodejs16.x
      CodeUri: ./src
      Policies:
        - DynamoDBCrudPolicy: 
            TableName: user-data
        - AWSLambdaBasicExecutionRole
      Events:
        UserDataAPI:
          Type: Api
          Properties:
            Path: /userdata
            Method: POST

  UserDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: user-data
      AttributeDefinitions:
        - AttributeName: UserID
          AttributeType: S
      KeySchema:
        - AttributeName: UserID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
